apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mpacer.fullname" . }}
  labels:
    {{- include "mpacer.labels" . | nindent 4 }}
data:
  MPACER_ENV: {{ .Values.config.environment | quote }}
  MPACER_BIND: {{ printf "0.0.0.0:%v" .Values.service.port | quote }}
  MPACER_PUBLIC_URL: {{ .Values.config.publicUrl | quote }}
  MPACER_COOKIE_SECURE: {{ .Values.config.cookieSecure | quote }}
  MPACER_DEV_AUTH: {{ .Values.config.devAuth | quote }}
  RUST_LOG: {{ .Values.config.rustLog | quote }}
